kind: pipeline
name: build
type: ssh

clone: 
  disable: true
server:
  host: tio-454.local
  user: mdmserviceuser
  # password: 1234
  ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFXiIDNN7m4lEXnxKU24jYY5jEKZ8GBmpaYKKhZeHvFKtNmQTtjJoxMLQLKJi3wUz4Hl1tJkKPbMNFIvaZjDct5ir6VJfTVqHk6OYVqdTnSn2uxMhiVKvBW4OjhYoBnvBLzpJlPk6B/E70IzqxSDGPy0v0f1HF6DM3jmWp76GV+3LvwBhU+86N9zVmXm25ef4FZBeHC+w7yYswZFnrqL1qgMX4Jp0Jk52r8/ErlbAVM1JUAdM1Ab9VzlnNAg7vG6TrKDzIV8iu4/X7M81a8fCYF3mpc3l7qJy0nBMJ/om6TCuO15leZaSLZM0kCZds2FFGP1HFXoGjRjpCGxWa9/VXWguw+9ztMlapyjrp+pB0IqT183z8FZKDW2g4DP7e7FQnLMgNZs8OvsNX8Pz6b3PgAsrcZWYwZq7kkN3nudGif0auoHiZEOvo9/jHH49U9wSnt//LJFTAPA15sMdQ/dHv61bArUfu+9wzN1L+m58d4fg7paakkZl2MiFw79+Sbs8= shobi@CCFs-MBP.fritz.box"

steps:
  - name: clone
    commands:
      - pwd
    environment: 
      HOME: ~/
  - name: build
    commands:
      - bash test.sh
      - echo hello world
      - hostname
      - pwd
      - whoami
      - cat /Users/mdm.serviceuser/.zshrc
      - echo $SHELL
      - echo $PATH
      - export PATH="/Users/mdm.serviceuser/Library/Android/sdk/tools:$PATH"
      - export PATH="/Users/mdm.serviceuser/Library/Android/sdk/platform-tools:$PATH"
      - echo $PATH
      - /usr/bin/xcodebuild -version
      - xcrun simctl list
      - cd ~ && pwd
  - name: keychain test
    environment:
      MDM_SERVICE_USER_PASSWORD: 1234
    commands:
      - security find-identity -vp codesigning
      - export KEYCHAIN_NAME=login.keychain
      - security create-keychain -p keychainPassword testkeychain
      - security list-keychains -d user -s  testkeychain
      - security list-keychains -d user
      - security list-keychains
      - security unlock-keychain -p '1234' "/Library/Keychains/System.keychain"
      - security find-identity -v -p codesigning
      -